// Objective-C API for talking to Hello Go package.
//   gobind -lang=objc Hello
//
// File is generated by gobind. Do not edit.

#ifndef __Hello_H__
#define __Hello_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Get Version of the library
 */
FOUNDATION_EXPORT NSString* _Nonnull HelloGetVersion(void);

FOUNDATION_EXPORT NSString* _Nonnull HelloGreetings(NSString* _Nullable name);

#endif
